In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [4]:
df = pd.read_csv("Data/Hands-On-Gradient-Boosting-with-XGBoost-and-Scikit-learn/Chapter10/student-por.csv",
                sep=";")

In [5]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,NaN,18.0,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,NaN,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15.0,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15.0,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16.0,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [6]:
df.isnull().sum()

school        0
sex           1
age           1
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      1
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [7]:
df[df.isna().any(axis=1)]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,NaN,18.0,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,NaN,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11

In [8]:
pd.options.display.max_columns = None

In [9]:
df[df.isna().any(axis=1)]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,NaN,18.0,U,GT3,A,4,4,at_home,teacher,course,NaN,2,2,0,yes,no,no,no,yes,yes,no,no,4,3,4,1,1,3,4,0,11,11
1,GP,F,NaN,U,GT3,T,1,1,at_home,other,course,father,1,2,0,no,yes,no,no,no,yes,yes,no,5,3,3,1,1,3,2,9,11,11

In [10]:
df['age'].fillna(-999.0, inplace=True)

In [11]:
df['sex'].fillna(df['sex'].mode(), inplace=True)

In [12]:
df['guardian'].fillna(df['guardian'].mode(),inplace=True)

In [13]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18.0,U,GT3,A,4,4,at_home,teacher,course,mother,2,2,0,yes,no,no,no,yes,yes,no,no,4,3,4,1,1,3,4,0,11,11
1,GP,F,-999.0,U,GT3,T,1,1,at_home,other,course,father,1,2,0,no,yes,no,no,no,yes,yes,no,5,3,3,1,1,3,2,9,11,11
2,GP,F,15.0,U,LE3,T,1,1,at_home,other,other,mother,1,2,0,yes,no,no,no,yes,yes,yes,no,4,3,2,2,3,3,6,12,13,12
3,GP,F,15.0,U,GT3,T,4,2,health,services,home,mother,1,3,0,no,yes,no,yes,yes,yes,yes,yes,3,2,2,1,1,5,0,14,14,14
4,GP,F,16.0,U,GT3,T,3,3,other,other,home,father,1,2,0,no,yes,no,no,yes,yes,no,no,4,3,2,1,2,5,0,11,13,13

In [16]:
cat_cols = df.columns[df.dtypes == object].tolist()

In [18]:
from sklearn.preprocessing import OneHotEncoder

In [19]:
ohe = OneHotEncoder()

In [20]:
hot = ohe.fit_transform(df[cat_cols])

In [21]:
print(hot)

  (0, 0)	1.0
  (0, 2)	1.0
  (0, 5)	1.0
  (0, 6)	1.0
  (0, 8)	1.0
  (0, 10)	1.0
  (0, 19)	1.0
  (0, 20)	1.0
  (0, 25)	1.0
  (0, 28)	1.0
  (0, 29)	1.0
  (0, 31)	1.0
  (0, 33)	1.0
  (0, 36)	1.0
  (0, 38)	1.0
  (0, 39)	1.0
  (0, 41)	1.0
  (1, 0)	1.0
  (1, 2)	1.0
  (1, 5)	1.0
  (1, 6)	1.0
  (1, 9)	1.0
  (1, 10)	1.0
  (1, 17)	1.0
  (1, 20)	1.0
  :	:
  (647, 27)	1.0
  (647, 29)	1.0
  (647, 31)	1.0
  (647, 33)	1.0
  (647, 35)	1.0
  (647, 38)	1.0
  (647, 40)	1.0
  (647, 41)	1.0
  (648, 1)	1.0
  (648, 3)	1.0
  (648, 4)	1.0
  (648, 7)	1.0
  (648, 9)	1.0
  (648, 13)	1.0
  (648, 17)	1.0
  (648, 20)	1.0
  (648, 25)	1.0
  (648, 27)	1.0
  (648, 29)	1.0
  (648, 31)	1.0
  (648, 33)	1.0
  (648, 35)	1.0
  (648, 38)	1.0
  (648, 40)	1.0
  (648, 41)	1.0

In [22]:
hot

<649x43 sparse matrix of type '<class 'numpy.float64'>'
	with 11033 stored elements in Compressed Sparse Row format>

In [23]:
cold_df = df.select_dtypes(exclude=["object"])

In [24]:
cold_df.head()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,18.0,4,4,2,2,0,4,3,4,1,1,3,4,0,11,11
1,-999.0,1,1,1,2,0,5,3,3,1,1,3,2,9,11,11
2,15.0,1,1,1,2,0,4,3,2,2,3,3,6,12,13,12
3,15.0,4,2,1,3,0,3,2,2,1,1,5,0,14,14,14
4,16.0,3,3,1,2,0,4,3,2,1,2,5,0,11,13,13

In [25]:
from scipy.sparse import csr_matrix

In [26]:
cold = csr_matrix(cold_df)

In [27]:
from scipy.sparse import hstack

In [28]:
final_sparse_matrix = hstack((hot, cold))

In [29]:
final_df = pd.DataFrame(final_sparse_matrix.toarray())

In [30]:
final_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58
0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,18.0,4.0,4.0,2.0,2.0,0.0,4.0,3.0,4.0,1.0,1.0,3.0,4.0,0.0,11.0,11.0
1,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,-999.0,1.0,1.0,1.0,2.0,0.0,5.0,3.0,3.0,1.0,1.0,3.0,2.0,9.0,11.0,11.0
2,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,15.0,1.0,1.0,1.0,2.0,0.0,4.0,3.0,2.0,2.0,3.0,3.0,6.0,12.0,13.0,12.0
3,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,15.0,4.0,2.0,1.0,3.0,0.0,3.0,2.0,2.0,1.0,1.0,5.0,0.0,14.0,14.0,14.0
4,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,16.0,3.0,3.0,1.0,2.0,0.0,4.0,3.0,2.0,1.0,2.0,5.0,0.0,11.0,13.0,13.0

In [31]:
from sklearn.base import TransformerMixin

In [32]:
class NullValueImputer(TransformerMixin):
    def __init__(self):
        None
    def fit(self, X, y = None):
        return self
    def transform(self, X, y= None):
        for column in X.columns.tolist():
            if column in X.columns[X.dtypes == object].tolist():
                X[column].fillna(X[column].mode(), inplace = True)
            else:
                X[column].fillna(-999.0, inplace=True)
        return X

In [33]:
df = pd.read_csv("Data/Hands-On-Gradient-Boosting-with-XGBoost-and-Scikit-learn/Chapter10/student-por.csv",
                sep= ";")

In [34]:
nvi = NullValueImputer().fit_transform(df)

In [35]:
nvi.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18.0,U,GT3,A,4,4,at_home,teacher,course,mother,2,2,0,yes,no,no,no,yes,yes,no,no,4,3,4,1,1,3,4,0,11,11
1,GP,F,-999.0,U,GT3,T,1,1,at_home,other,course,father,1,2,0,no,yes,no,no,no,yes,yes,no,5,3,3,1,1,3,2,9,11,11
2,GP,F,15.0,U,LE3,T,1,1,at_home,other,other,mother,1,2,0,yes,no,no,no,yes,yes,yes,no,4,3,2,2,3,3,6,12,13,12
3,GP,F,15.0,U,GT3,T,4,2,health,services,home,mother,1,3,0,no,yes,no,yes,yes,yes,yes,yes,3,2,2,1,1,5,0,14,14,14
4,GP,F,16.0,U,GT3,T,3,3,other,other,home,father,1,2,0,no,yes,no,no,yes,yes,no,no,4,3,2,1,2,5,0,11,13,13

In [36]:
class SparseMatrix(TransformerMixin):
    def __init__(self):
        None
    def fit(self, X, y = None):
        return self
    def transform(self, X, y = None):
        cat_cols = X.columns[X.dtypes == object].tolist()
        ohe = OneHotEncoder()
        hot = ohe.fit_transform(X[cat_cols])
        cold_df = X.select_dtypes(exclude = ["object"])
        cold = csr_matrix(cold_df)
        final_sparse_matrix = hstack((hot, cold))
        final_csr_matrix = final_sparse_matrix.tocsr()
        return final_csr_matrix

In [37]:
sm = SparseMatrix().fit_transform(nvi)

In [38]:
print(sm)

  (0, 0)	1.0
  (0, 2)	1.0
  (0, 5)	1.0
  (0, 6)	1.0
  (0, 8)	1.0
  (0, 10)	1.0
  (0, 19)	1.0
  (0, 20)	1.0
  (0, 25)	1.0
  (0, 28)	1.0
  (0, 29)	1.0
  (0, 31)	1.0
  (0, 33)	1.0
  (0, 36)	1.0
  (0, 38)	1.0
  (0, 39)	1.0
  (0, 41)	1.0
  (0, 43)	18.0
  (0, 44)	4.0
  (0, 45)	4.0
  (0, 46)	2.0
  (0, 47)	2.0
  (0, 49)	4.0
  (0, 50)	3.0
  (0, 51)	4.0
  :	:
  (648, 20)	1.0
  (648, 25)	1.0
  (648, 27)	1.0
  (648, 29)	1.0
  (648, 31)	1.0
  (648, 33)	1.0
  (648, 35)	1.0
  (648, 38)	1.0
  (648, 40)	1.0
  (648, 41)	1.0
  (648, 43)	18.0
  (648, 44)	3.0
  (648, 45)	2.0
  (648, 46)	3.0
  (648, 47)	1.0
  (648, 49)	4.0
  (648, 50)	4.0
  (648, 51)	1.0
  (648, 52)	3.0
  (648, 53)	4.0
  (648, 54)	5.0
  (648, 55)	4.0
  (648, 56)	10.0
  (648, 57)	11.0
  (648, 58)	11.0

In [39]:
df = pd.read_csv("Data/Hands-On-Gradient-Boosting-with-XGBoost-and-Scikit-learn/Chapter10/student-por.csv",
                sep=";")

In [40]:
X = df.iloc[:,:-3]
y = df.iloc[:,-1]

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=2)

In [43]:
from sklearn.pipeline import Pipeline

In [44]:
data_pipeline = Pipeline([('null_inputer',NullValueImputer()),
                         ('sparse',SparseMatrix())])

In [45]:
X_train_transformed = data_pipeline.fit_transform(X_train)

In [46]:
X_train_transformed.shape

(486, 56)

In [47]:
import numpy as np
from sklearn.model_selection import GridSearchCV, cross_val_score, KFold
from sklearn.metrics import mean_squared_error as MSE
from xgboost import XGBRegressor

In [48]:
y_train.value_counts()

11    82
10    75
13    58
12    53
14    42
15    36
9     29
16    27
8     26
17    24
18    14
0     10
7      7
6      1
19     1
5      1
Name: G3, dtype: int64

In [49]:
kfold = KFold(n_splits= 5, shuffle=True, random_state=2)

In [50]:
def cross_val(model):
    scores = cross_val_score(model, X_train_transformed, y_train, scoring="neg_root_mean_squared_error",
                            cv=kfold)
    rmse = (-scores.mean())
    return rmse

In [51]:
cross_val(XGBRegressor(missing = -999.0))

2.970224842324008

In [53]:
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X_train_transformed, y_train, random_state=2)

In [54]:
def n_estimators(model):
    eval_set = [(X_test_2, y_test_2)]
    eval_metric = "rmse"
    model.fit(X_train_2, y_train_2, eval_metric = eval_metric, eval_set = eval_set, early_stopping_rounds = 100)
    y_pred = model.predict(X_test_2)
    rmse = MSE(y_test_2, y_pred)**0.5
    return rmse

In [55]:
n_estimators(XGBRegressor(n_estimators = 5000, missing = -999.0))

[0]	validation_0-rmse:8.49176
[1]	validation_0-rmse:6.31389
[2]	validation_0-rmse:4.97728
[3]	validation_0-rmse:4.16009
[4]	validation_0-rmse:3.66768
[5]	validation_0-rmse:3.42965
[6]	validation_0-rmse:3.28449
[7]	validation_0-rmse:3.18376
[8]	validation_0-rmse:3.15987
[9]	validation_0-rmse:3.16607
[10]	validation_0-rmse:3.16598
[11]	validation_0-rmse:3.13184
[12]	validation_0-rmse:3.13545
[13]	validation_0-rmse:3.13216
[14]	validation_0-rmse:3.13269
[15]	validation_0-rmse:3.13168
[16]	validation_0-rmse:3.10129
[17]	validation_0-rmse:3.10436
[18]	validation_0-rmse:3.10149
[19]	validation_0-rmse:3.10755
[20]	validation_0-rmse:3.10326
[21]	validation_0-rmse:3.09872
[22]	validation_0-rmse:3.09888
[23]	validation_0-rmse:3.09904
[24]	validation_0-rmse:3.10572
[25]	validation_0-rmse:3.10126
[26]	validation_0-rmse:3.09657
[27]	validation_0-rmse:3.09536
[28]	validation_0-rmse:3.09664
[29]	validation_0-rmse:3.09789
[30]	validation_0-rmse:3.09803
[31]	validation_0-rmse:3.09336
[32]	validation_0-rmse:3.10293
[33]	validation_0-rmse:3.10499
[34]	validation_0-rmse:3.10400
[35]	validation_0-rmse:3.10528
[36]	validation_0-rmse:3.10506
[37]	validation_0-rmse:3.10678
[38]	validation_0-rmse:3.10561
[39]	validation_0-rmse:3.10670
[40]	validation_0-rmse:3.10500
[41]	validation_0-rmse:3.10732
[42]	validation_0-rmse:3.10943
[43]	validation_0-rmse:3.10759
[44]	validation_0-rmse:3.10615
[45]	validation_0-rmse:3.10585
[46]	validation_0-rmse:3.10694
[47]	validation_0-rmse:3.10620
[48]	validation_0-rmse:3.10847
[49]	validation_0-rmse:3.10736
[50]	validation_0-rmse:3.10631
[51]	validation_0-rmse:3.10588
[52]	validation_0-rmse:3.10461
[53]	validation_0-rmse:3.10369
[54]	validation_0-rmse:3.10464
[55]	validation_0-rmse:3.10586
[56]	validation_0-rmse:3.10595
[57]	validation_0-rmse:3.10686
[58]	validation_0-rmse:3.10753
[59]	validation_0-rmse:3.10755
[60]	validation_0-rmse:3.10811
[61]	validation_0-rmse:3.10870
[62]	validation_0-rmse:3.10863
[63]	validation_0-rmse:3.10835
[64]	validation_0-rmse:3.10709
[65]	validation_0-rmse:3.10723
[66]	validation_0-rmse:3.10674
[67]	validation_0-rmse:3.10686
[68]	validation_0-rmse:3.10657
[69]	validation_0-rmse:3.10570
[70]	validation_0-rmse:3.10630
[71]	validation_0-rmse:3.10502
[72]	validation_0-rmse:3.10345
[73]	validation_0-rmse:3.10346
[74]	validation_0-rmse:3.10279
[75]	validation_0-rmse:3.10313
[76]	validation_0-rmse:3.10310
[77]	validation_0-rmse:3.10331
[78]	validation_0-rmse:3.10347
[79]	validation_0-rmse:3.10344
[80]	validation_0-rmse:3.10341
[81]	validation_0-rmse:3.10313
[82]	validation_0-rmse:3.10322
[83]	validation_0-rmse:3.10343
[84]	validation_0-rmse:3.10377
[85]	validation_0-rmse:3.10415
[86]	validation_0-rmse:3.10419
[87]	validation_0-rmse:3.10416
[88]	validation_0-rmse:3.10419
[89]	validation_0-rmse:3.10423
[90]	validation_0-rmse:3.10456
[91]	validation_0-rmse:3.10446
[92]	validation_0-rmse:3.10460
[93]	validation_0-rmse:3.10455
[94]	validation_0-rmse:3.10462
[95]	validation_0-rmse:3.10449
[96]	validation_0-rmse:3.10437
[97]	validation_0-rmse:3.10445
[98]	validation_0-rmse:3.10446
[99]	validation_0-rmse:3.10442
[100]	validation_0-rmse:3.10438
[101]	validation_0-rmse:3.10441
[102]	validation_0-rmse:3.10442
[103]	validation_0-rmse:3.10438
[104]	validation_0-rmse:3.10438
[105]	validation_0-rmse:3.10434
[106]	validation_0-rmse:3.10433
[107]	validation_0-rmse:3.10433
[108]	validation_0-rmse:3.10426
[109]	validation_0-rmse:3.10425
[110]	validation_0-rmse:3.10432
[111]	validation_0-rmse:3.10432
[112]	validation_0-rmse:3.10441
[113]	validation_0-rmse:3.10442
[114]	validation_0-rmse:3.10439
[115]	validation_0-rmse:3.10437
[116]	validation_0-rmse:3.10438
[117]	validation_0-rmse:3.10440
[118]	validation_0-rmse:3.10446
[119]	validation_0-rmse:3.10448
[120]	validation_0-rmse:3.10448
[121]	validation_0-rmse:3.10450
[122]	validation_0-rmse:3.10450
[123]	validation_0-rmse:3.10450
[124]	validation_0-rmse:3.10450
[125]	validation_0-rmse:3.10450
[126]	validation_0-rmse:3.10450
[127]	validation_0-rmse:3.10450
[128]	validation_0-rmse:3.10450
[129]	validation_0-rmse:3.10450
[130]	validation_0-rmse:3.10450
[131]	validation_0-rmse:3.10450

3.093361208225006

In [58]:
def grid_search(params, reg = XGBRegressor(missing = -999.0)):
    grid_reg = GridSearchCV(reg, params, scoring = "neg_mean_squared_error", cv=kfold)
    grid_reg.fit(X_train_transformed, y_train)
    best_params = grid_reg.best_params_
    print("Best Params : ", best_params)
    best_score = np.sqrt(-grid_reg.best_score_)
    print("Best Score : ", best_score)

In [59]:
grid_search(params={'max_depth' : [1,2,3,4,6,7,8],
                   'n_estimators' : [31]})

Best Params :  {'max_depth': 1, 'n_estimators': 31}
Best Score :  2.663443073302518

In [60]:
grid_search(params={'max_depth':[1, 2, 3],
                   'min_child_weight':[1,2,3,4,5],
                   'n_estimators':[31]})

Best Params :  {'max_depth': 1, 'min_child_weight': 1, 'n_estimators': 31}
Best Score :  2.663443073302518

In [61]:
grid_search(params= {'max_depth' : [2],
                    'min_child_weight' : [2, 3],
                    'subsample' : [0.5, 0.6, 0.7, 0.8, 0.9],
                    'n_estimators' : [31, 50]})

Best Params :  {'max_depth': 2, 'min_child_weight': 2, 'n_estimators': 31, 'subsample': 0.9}
Best Score :  2.679803933212046

In [62]:
grid_search(params = {'max_depth':[1],
                     'min_child_weight':[1,2,3],
                     'subsample':[0.6,0.7,0.8],
                     'colsample_bytree':[0.5,0.6,0.7,0.8,0.9,1],
                     'n_estimators':[50]})

Best Params :  {'colsample_bytree': 0.7, 'max_depth': 1, 'min_child_weight': 1, 'n_estimators': 50, 'subsample': 0.8}
Best Score :  2.6476064038006086

In [63]:
grid_search(params = {'max_depth':[1],
                     'min_child_weight':[3],
                     'subsample':[0.8],
                     'colsample_bytree':[0.9],
                      'colsample_bylevel':[0.6,0.7,0.8,0.9,1.0],
                      'colsample_bynode':[0.6,0.7,0.8,0.9,1.0],
                     'n_estimators':[50]})

Best Params :  {'colsample_bylevel': 0.9, 'colsample_bynode': 0.8, 'colsample_bytree': 0.9, 'max_depth': 1, 'min_child_weight': 3, 'n_estimators': 50, 'subsample': 0.8}
Best Score :  2.6571046733208834

In [64]:
X_test_transformed = data_pipeline.fit_transform(X_test)

In [65]:
model = XGBRegressor(max_depth = 2, min_child_weight = 3, subsample = 0.9, colsample_bytree = 0.8,
                    gamma = 2, missing = -999.0)

In [66]:
model.fit(X_train_transformed, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=0.8,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, gamma=2, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=2, max_leaves=0, min_child_weight=3,
             missing=-999.0, monotone_constraints='()', n_estimators=100,
             n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
             reg_alpha=0, reg_lambda=1, ...)

In [67]:
y_pred = model.predict(X_test_transformed)
rmse = MSE(y_test, y_pred)**0.5
rmse

2.9125343115306817

In [68]:
model = XGBRegressor(max_depth = 1, min_child_weight = 5, subsample = 0.6, colsample_bytree = 0.9,
                     colsample_bylevel = 0.9, colsample_bynode = 0.8, n_estimators = 50,
                    missing = -999.0)

In [69]:
model.fit(X_train_transformed, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=0.9, colsample_bynode=0.8, colsample_bytree=0.9,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=1, max_leaves=0, min_child_weight=5,
             missing=-999.0, monotone_constraints='()', n_estimators=50,
             n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
             reg_alpha=0, reg_lambda=1, ...)

In [70]:
y_pred = model.predict(X_test_transformed)
rmse = MSE(y_test, y_pred)**0.5
rmse

2.796200143322201

In [71]:
full_pipleine = Pipeline([('null_imputer',NullValueImputer()),
                         ('sparse',SparseMatrix()),
                         ('xgb',XGBRegressor(max_depth = 1, min_child_weight = 5, subsample = 0.6,
                                            colsample_bytree = 0.9, colsample_bylevel = 0.9,
                                            colsample_bynode = 0.8, missing = -999.0))])

In [72]:
full_pipleine.fit(X, y)

Pipeline(steps=[('null_imputer',
                 <__main__.NullValueImputer object at 0x0000019928A26CA0>),
                ('sparse',
                 <__main__.SparseMatrix object at 0x0000019928A26E50>),
                ('xgb',
                 XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
                              colsample_bylevel=0.9, colsample_bynode=0.8,
                              colsample_bytree=0.9, early_stopping_rounds=None,
                              enable_categorical=False, eval_metric=None,
                              ga...u_id=-1, grow_policy='depthwise',
                              importance_type=None, interaction_constraints='',
                              learning_rate=0.300000012, max_bin=256,
                              max_cat_to_onehot=4, max_delta_step=0,
                              max_depth=1, max_leaves=0, min_child_weight=5,
                              missing=-999.0, monotone_constraints='()',
                              n_estimators=100, n_jobs=0, num_parallel_tree=1,
                              predictor='auto', random_state=0, reg_alpha=0,
                              reg_lambda=1, ...))])

In [73]:
new_data = X_test
full_pipleine.predict(new_data)

array([13.775518 ,  8.206751 , 10.909969 , 14.075367 , 12.31351  ,
       11.5154085, 13.911582 , 11.932506 , 10.562169 , 13.41987  ,
       12.791853 ,  9.413459 , 12.69037  , 12.920808 , 13.897951 ,
        8.770833 ,  9.648426 , 10.115617 , 15.999148 , 10.3910055,
       12.58394  , 13.37267  ,  6.442958 , 12.256222 ,  7.531832 ,
        8.748239 ,  9.9837675, 13.782697 , 13.988778 , 12.016966 ,
       11.044688 , 11.553163 , 15.522663 ,  8.318498 , 11.345538 ,
       12.905847 , 11.860768 , 10.522468 ,  8.687595 , 12.6182995,
       11.502619 , 11.408965 , 11.694238 , 13.804838 , 13.885608 ,
       15.187097 , 12.218502 , 12.840124 , 12.939832 , 12.04681  ,
       14.321343 ,  6.0404873,  5.8603544, 12.422976 , 14.448407 ,
        9.9005575, 12.53927  ,  8.290919 , 13.381123 , 11.97324  ,
       13.4832   ,  6.684698 ,  9.445383 , 12.257223 , 14.240899 ,
       10.537201 , 13.948392 , 13.880086 , 11.759    , 10.621063 ,
       11.470315 , 13.429966 , 12.317644 ,  7.3200483, 13.379705 ,
       12.31567  , 13.648816 , 14.675237 , 12.238883 , 10.571692 ,
       12.348517 ,  7.1138215,  9.9284315, 11.915328 , 13.217128 ,
       10.496791 ,  8.945163 , 11.778383 , 15.400422 , 14.764176 ,
       11.051682 ,  9.931942 , 14.077378 , 11.86171  , 12.29553  ,
       13.475249 , 12.314572 ,  7.9844594, 13.329631 , 14.623818 ,
       13.824771 ,  8.682549 , 11.603197 , 12.298408 , 13.293579 ,
       15.110618 , 12.663773 , 10.06467  ,  9.617799 , 13.604691 ,
        6.9077168, 10.794921 , 13.235801 , 10.756703 , 14.449884 ,
       11.858546 , 11.917375 , 10.994822 , 12.321581 , 11.989097 ,
       13.883973 ,  8.5053215, 12.892388 , 10.0191   , 13.492354 ,
       11.730002 , 15.088704 , 14.781364 , 11.485618 , 13.796464 ,
       10.365253 , 14.205172 ,  8.846817 ,  9.213696 , 12.529458 ,
       13.343815 ,  9.719181 , 11.156821 , 13.677389 , 12.703609 ,
       10.192359 , 12.09495  , 12.655838 , 12.4940815, 13.446088 ,
       10.977543 , 12.491962 , 13.410554 , 14.378498 , 13.22635  ,
        8.886384 , 10.523721 , 12.294043 ,  7.0014687,  8.135691 ,
       11.737048 , 14.084939 , 13.2686825, 13.090377 , 10.3726   ,
       11.910177 , 13.423771 ,  9.2532   ], dtype=float32)